### PR TITLE
Update maven-bundle-plugin to 5.1.9 to allow JDK 17+ to be used to build

### LINKED ISSUE #193: Unable to build master branch with JDK 17 (or newer)
The hardcoded maven-bundle-plugin at version 4.0.0 is incompatible with JDK versions 17 and newer.

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Jetty :: Jasper :: Project 10.0.27-SNAPSHOT:
[INFO] 
[INFO] Jetty :: Jasper :: Project ......................... SUCCESS [  0.571 s]
[INFO] MortBay :: Apache EL :: API and Implementation ..... FAILURE [  0.942 s]
[INFO] MortBay :: Apache Jasper :: JSP Implementation ..... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.253 s
[INFO] Finished at: 2023-12-06T08:35:05-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.felix:maven-bundle-plugin:4.0.0:manifest (bundle-manifest) on project apache-el: Execution bundle-manifest of goal org.apache.felix:maven-bundle-plugin:4.0.0:manifest failed.: ConcurrentModificationException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :apache-el
```

I went ahead and updated the comment about it with commit a1b73c685e3c0a2cae764d6c5ab3d13890a256e7

This should really be addressed.

### PR DESCRIPTION
**Pull request by joakime**
Update the maven-bundle-plugin to allow JDK17+ to be used.

The original JDK11 (with m-bundle-p v4.0.0) manifest looks like this ...

**apache-el-<ver>.jar**

```
Manifest-Version: 1.0
Automatic-Module-Name: org.mortbay.apache.el
Bnd-LastModified: 1701872744230
Build-Jdk: 11.0.20.1
Built-By: joakim
Bundle-Classpath: .
Bundle-Description: A rebundling of Apache Tomcat Jasper to remove the t
 omcat server dependencies,    so that the JSP engine can be used by the
  Eclipse Jetty project.
Bundle-License: http://www.apache.org/licenses/LICENSE-2.0
Bundle-ManifestVersion: 2
Bundle-Name: Mortbay Apache EL API and Implementation
Bundle-RequiredExecutionEnvironment: JavaSE-1.7
Bundle-SymbolicName: org.mortbay.jasper.apache-el
Bundle-Version: 10.0.27
Created-By: Apache Maven Bundle Plugin
Export-Package: jakarta.el;version="4.0.0.SNAPSHOT",org.apache.el;versio
 n="10.0.27",org.apache.el.lang;version="10.0.27",org.apache.el.stream;v
 ersion="10.0.27",org.apache.el.parser;version="10.0.27",org.apache.el.u
 til;version="10.0.27"
Implementation-Version: 10.0.27
Import-Package: jakarta.servlet.jsp;version="3.0";resolution:=optional,j
 akarta.servlet.jsp.el;version="3.0";resolution:=optional,jakarta.servle
 t.jsp.tagext;version="3.0";resolution:=optional
Specification-Version: 3.0
Tool: Bnd-4.0.0.201805111645
```

**apache-jsp-<ver>.jar**

```
Manifest-Version: 1.0
Automatic-Module-Name: org.mortbay.apache.jasper
Bnd-LastModified: 1701872751931
Build-Jdk: 11.0.20.1
Built-By: joakim
Bundle-Classpath: .
Bundle-Description: A rebundling of Apache Tomcat Jasper to remove the t
 omcat server dependencies,    so that the JSP engine can be used by the
  Eclipse Jetty project.
Bundle-License: http://www.apache.org/licenses/LICENSE-2.0
Bundle-ManifestVersion: 2
Bundle-Name: Mortbay Jasper
Bundle-RequiredExecutionEnvironment: JavaSE-1.7
Bundle-SymbolicName: org.mortbay.jasper.apache-jsp
Bundle-Version: 10.0.27
Created-By: Apache Maven Bundle Plugin
Export-Package: org.apache.juli.logging;version="10.0.27",org.apache.tom
 cat;version="10.0.27",org.apache.tomcat.util.compat;version="10.0.27",o
 rg.apache.tomcat.util.scan;version="10.0.27",org.apache.tomcat.util.fil
 e;version="10.0.27",org.apache.tomcat.util.digester;version="10.0.27",o
 rg.apache.tomcat.util.descriptor.tagplugin;version="10.0.27",org.apache
 .tomcat.util.descriptor.tld;version="10.0.27",org.apache.tomcat.util.de
 scriptor.web;version="10.0.27",org.apache.tomcat.util;version="10.0.27"
 ,org.apache.tomcat.util.buf;version="10.0.27",org.apache.tomcat.util.re
 s;version="10.0.27",org.apache.tomcat.util.security;version="10.0.27",j
 akarta.servlet.jsp;version="3.0",jakarta.servlet.jsp.el;version="3.0",j
 akarta.servlet.jsp.tagext;version="3.0",jakarta.servlet.jsp.resources;v
 ersion="3.0",org.apache.jasper;version="10.0.27",org.apache.jasper.comp
 iler;version="10.0.27",org.apache.jasper.compiler.tagplugin;version="10
 .0.27",org.apache.jasper.el;version="10.0.27",org.apache.jasper.resourc
 es;version="10.0.27",org.apache.jasper.runtime;version="10.0.27",org.ap
 ache.jasper.security;version="10.0.27",org.apache.jasper.servlet;versio
 n="10.0.27",org.apache.jasper.tagplugins.jstl;version="10.0.27",org.apa
 che.jasper.tagplugins.jstl.core;version="10.0.27",org.apache.jasper.uti
 l;version="10.0.27",org.apache.jasper.xmlparser;version="10.0.27"
Implementation-Version: 10.0.27
Import-Package: jakarta.el;version="4.0",javax.naming,javax.net.ssl,jaka
 rta.servlet;version="5.0",jakarta.servlet.annotation;version="5.0",jaka
 rta.servlet.descriptor;version="5.0",jakarta.servlet.http;version="5.0"
 ,jakarta.servlet.resources;version="5.0",javax.xml.parsers,org.apache.e
 l.util;version="[10.0,11)",org.apache.tomcat.util.descriptor;version="1
 0.0.0";resolution:=optional,org.apache.tomcat.util.descriptor.tagplugin
 ;version="10.0.0";resolution:=optional,org.eclipse.jdt.core.compiler,or
 g.eclipse.jdt.internal.compiler,org.eclipse.jdt.internal.compiler.class
 fmt,org.eclipse.jdt.internal.compiler.env,org.eclipse.jdt.internal.comp
 iler.impl,org.eclipse.jdt.internal.compiler.problem,org.xml.sax,org.xml
 .sax.ext,org.xml.sax.helpers
Require-Capability: osgi.serviceloader;filter:="(osgi.serviceloader=org.
 apache.juli.logging.Log)";resolution:=optional;cardinality:=multiple,os
 gi.extender;filter:="(osgi.extender=osgi.serviceloader.processor)"
Specification-Version: 2.3
Tool: Bnd-4.0.0.201805111645
```

Fixes #193

### CODE REVIEW

**Comment by joakime** [comment]
Simply upgrading the maven-bundle-plugin to 5.1.9 produces a different manifest (as expected).

Here's the diffs from the m-bundle-plugin 4.0.0 produced manifests.

**apache-el-<ver>.jar**

``` diff
--- apache-el-10.0.27-4.0.0-manifest.txt	2023-12-06 08:27:47.973722933 -0600
+++ apache-el-10.0.27-5.1.9-manifest-jdk11.txt	2023-12-06 08:30:27.637235657 -0600
@@ -1,8 +1,7 @@
 Manifest-Version: 1.0
 Automatic-Module-Name: org.mortbay.apache.el
-Bnd-LastModified: 1701872744230
-Build-Jdk: 11.0.20.1
-Built-By: joakim
+Bnd-LastModified: 1701872949288
+Build-Jdk-Spec: 11
 Bundle-Classpath: .
 Bundle-Description: A rebundling of Apache Tomcat Jasper to remove the t
  omcat server dependencies,    so that the JSP engine can be used by the
@@ -13,14 +12,16 @@
 Bundle-RequiredExecutionEnvironment: JavaSE-1.7
 Bundle-SymbolicName: org.mortbay.jasper.apache-el
 Bundle-Version: 10.0.27
-Created-By: Apache Maven Bundle Plugin
+Created-By: Apache Maven Bundle Plugin 5.1.9
 Export-Package: jakarta.el;version="4.0.0.SNAPSHOT",org.apache.el;versio
  n="10.0.27",org.apache.el.lang;version="10.0.27",org.apache.el.stream;v
  ersion="10.0.27",org.apache.el.parser;version="10.0.27",org.apache.el.u
  til;version="10.0.27"
 Implementation-Version: 10.0.27
-Import-Package: jakarta.servlet.jsp;version="3.0";resolution:=optional,j
- akarta.servlet.jsp.el;version="3.0";resolution:=optional,jakarta.servle
- t.jsp.tagext;version="3.0";resolution:=optional
+Import-Package: jakarta.servlet.jsp;resolution:=optional,jakarta.servlet
+ .jsp.el;resolution:=optional,jakarta.servlet.jsp.tagext;resolution:=opt
+ ional
+Require-Capability: osgi.contract;osgi.contract=JavaJSP;filter:="(&(osgi
+ .contract=JavaJSP)(version=3.0.0))"
 Specification-Version: 3.0
-Tool: Bnd-4.0.0.201805111645
+Tool: Bnd-6.3.1.202206071316
```

The above manfiest introduces a `Required-Capability` section, along with removing the `version` specifications in the `Import-Package` section.
This change seems appropriate, and doesn't appear to break anything.

**apache-jsp-<ver>.jar**

``` diff
--- apache-jsp-10.0.27-4.0.0-manifest.txt	2023-12-06 08:27:29.469316839 -0600
+++ apache-jsp-10.0.27-5.1.9-manifest-jdk11.txt	2023-12-06 08:30:15.928977960 -0600
@@ -1,8 +1,7 @@
 Manifest-Version: 1.0
 Automatic-Module-Name: org.mortbay.apache.jasper
-Bnd-LastModified: 1701872751931
-Build-Jdk: 11.0.20.1
-Built-By: joakim
+Bnd-LastModified: 1701872956820
+Build-Jdk-Spec: 11
 Bundle-Classpath: .
 Bundle-Description: A rebundling of Apache Tomcat Jasper to remove the t
  omcat server dependencies,    so that the JSP engine can be used by the
@@ -13,7 +12,7 @@
 Bundle-RequiredExecutionEnvironment: JavaSE-1.7
 Bundle-SymbolicName: org.mortbay.jasper.apache-jsp
 Bundle-Version: 10.0.27
-Created-By: Apache Maven Bundle Plugin
+Created-By: Apache Maven Bundle Plugin 5.1.9
 Export-Package: org.apache.juli.logging;version="10.0.27",org.apache.tom
  cat;version="10.0.27",org.apache.tomcat.util.compat;version="10.0.27",o
  rg.apache.tomcat.util.scan;version="10.0.27",org.apache.tomcat.util.fil
@@ -49,4 +48,4 @@
  apache.juli.logging.Log)";resolution:=optional;cardinality:=multiple,os
  gi.extender;filter:="(osgi.extender=osgi.serviceloader.processor)"
 Specification-Version: 2.3
-Tool: Bnd-4.0.0.201805111645
+Tool: Bnd-6.3.1.202206071316
```

The above manifest is functionally identical to what was produced by m-bundle-p 4.0.0

One other thing noticed was that `Bundle-RequiredExecutionEnvironment` is out of date, still referencing `1.7`, even though `master` requires JDK 11 at minimum.

**Comment by janbartel** [comment]
Mmmm, we seem to have `master` and `apache-10.0.x` that should be the same, and should only be one of them. I just merged `master` into the `apache-10.0.x` branch, but we shouldn't have 2 copies like that, maybe we should remove `master` and make `apache-10.0.x` the default? Then when `jetty-12.0.x` becomes the default branch, we should move default to `apache-10.1.x`. WDYT?

**Comment by olamy** [comment]
Yup some cleanup would be good as branches are really confusing,
 I would prefer having `master` as last Apache Tomcat version (11.x) I would find it more logical and we will (probably?) need it soon.

**Comment by janbartel** [comment]
@olamy what about if we had no `master`, same as jetty, just the named branches?

**Comment by olamy** [comment]
@janbartel yes even better, less confusing :) and inline with what we do with jetty project

**Comment by janbartel** [comment]
@joakime ok, so how about you remake this PR against the `jetty-10.0.x` branch and then we can delete `master`? Then we should do the same for all of the other branches of this project as well.

**Comment by joakime** [comment]
How about this ..

1. We rename `master` to `apache-11.0.x`
2. Make `apache-11.0.x` the new default branch.
3. Setup dependabot / GHA / Jenkins to only target `apache-11.0.x` (ee11), `apache-10.1.x` (ee10), `apache-10.0.x` (ee9), and `apache-9` (ee8) branches.
4. File new PRs to update maven-bundle-plugin in each of the 4 branches above, listing the changes to the MANIFEST.MF before/after the update as a diff in comments on each PR (so we can review the impact)

**Comment by olamy** [comment]
perfect!

**Pull request closed without merging**
